API_KEY = 'trnsl.1.1.20210425T142939Z.70e879d43751cd42.8c41b6064daa44da3bbffa270ffc8012644885d3'
API_URL = 'https://translate.yandex.net/api/v1.5/tr.json/translate'
# API_HOST = 'translated-mymemory---translation-memory.p.rapidapi.com'
TOKEN = '1851965886:AAE2iVVwWq3ihuaNnaOrgfa-W1bqDn6XZls'
# @translatorsiriusbot
# 1606352297:AAHcEj_5VsoPt3xsn8Z6wPPzop6gc5wjFio - запасной @yandexlyceum2yearbot


POSSIBLE_LANGS = {'afrikaans': 'af',
                  'albanian': 'sq',
                  'amharic': 'am',
                  'arabic': 'ar',
                  'armenian': 'hy',
                  'azerbaijani': 'az',
                  'basque': 'eu',
                  'belarusian': 'be',
                  'bengali': 'bn',
                  'bosnian': 'bs',
                  'bulgarian': 'bg',
                  'catalan': 'ca',
                  'cebuano': 'ceb',
                  'chichewa': 'ny',
                  'chinese': 'zh',
                  'chinese (simplified)': 'zh-cn',
                  'chinese (traditional)': 'zh-tw',
                  'corsican': 'co',
                  'croatian': 'hr',
                  'czech': 'cs',
                  'danish': 'da',
                  'dutch': 'nl',
                  'english': 'en',
                  'esperanto': 'eo',
                  'estonian': 'et',
                  'filipino': 'tl',
                  'finnish': 'fi',
                  'french': 'fr',
                  'frisian': 'fy',
                  'galician': 'gl',
                  'georgian': 'ka',
                  'german': 'de',
                  'greek': 'el',
                  'gujarati': 'gu',
                  'haitian creole': 'ht',
                  'hausa': 'ha',
                  'hawaiian': 'haw',
                  'hebrew': 'iw',
                  'hindi': 'hi',
                  'hmong': 'hmn',
                  'hungarian': 'hu',
                  'icelandic': 'is',
                  'igbo': 'ig',
                  'indonesian': 'id',
                  'irish': 'ga',
                  'italian': 'it',
                  'japanese': 'ja',
                  'javanese': 'jw',
                  'kannada': 'kn',
                  'kazakh': 'kk',
                  'khmer': 'km',
                  'korean': 'ko',
                  'kurdish (kurmanji)': 'ku',
                  'kyrgyz': 'ky',
                  'lao': 'lo',
                  'latin': 'la',
                  'latvian': 'lv',
                  'lithuanian': 'lt',
                  'luxembourgish': 'lb',
                  'macedonian': 'mk',
                  'malagasy': 'mg',
                  'malay': 'ms',
                  'malayalam': 'ml',
                  'maltese': 'mt',
                  'maori': 'mi',
                  'marathi': 'mr',
                  'mongolian': 'mn',
                  'myanmar (burmese)': 'my',
                  'nepali': 'ne',
                  'norwegian': 'no',
                  'pashto': 'ps',
                  'persian': 'fa',
                  'polish': 'pl',
                  'portuguese': 'pt',
                  'punjabi': 'pa',
                  'romanian': 'ro',
                  'russian': 'ru',
                  'samoan': 'sm',
                  'scots gaelic': 'gd',
                  'serbian': 'sr',
                  'sesotho': 'st',
                  'shona': 'sn',
                  'sindhi': 'sd',
                  'sinhala': 'si',
                  'slovak': 'sk',
                  'slovenian': 'sl',
                  'somali': 'so',
                  'spanish': 'es',
                  'sundanese': 'su',
                  'swahili': 'sw',
                  'swedish': 'sv',
                  'tajik': 'tg',
                  'tamil': 'ta',
                  'telugu': 'te',
                  'thai': 'th',
                  'turkish': 'tr',
                  'ukrainian': 'uk',
                  'urdu': 'ur',
                  'uzbek': 'uz',
                  'vietnamese': 'vi',
                  'welsh': 'cy',
                  'xhosa': 'xh',
                  'yiddish': 'yi',
                  'yoruba': 'yo',
                  'zulu': 'zu'}


